In [1]:
#np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [12]:
#np.arange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [18]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
# np.random
np.random.random((3,4))

array([[0.22805003, 0.88547109, 0.93470839, 0.39169252],
       [0.73844886, 0.8977804 , 0.32321629, 0.73004691],
       [0.77274877, 0.83148304, 0.13708901, 0.00225103]])

In [28]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [30]:
np.linspace(-5,5,8)

array([-5.        , -3.57142857, -2.14285714, -0.71428571,  0.71428571,
        2.14285714,  3.57142857,  5.        ])

In [32]:
np.linspace(-4,6,8)

array([-4.        , -2.57142857, -1.14285714,  0.28571429,  1.71428571,
        3.14285714,  4.57142857,  6.        ])

In [34]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [44]:
# ndim
a3.ndim

3

In [46]:
#shape
a3.shape

(2, 2, 2)

In [48]:
a3.shape
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [50]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [52]:
#itemsize
a3.itemsize

8

In [54]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [56]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations


In [70]:
a1 = np.arange(12).reshape((3,4))
a2 = np.arange(12,24).reshape((3,4))
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
# scalar operations

# arithmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [71]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
#relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [73]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [75]:
b = a1**2
b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [77]:
b[0:3,1:2]

array([[ 1],
       [25],
       [81]])

In [81]:
b[0:1,1:2]

array([[1]])

In [83]:
b[0:2,1:3]

array([[ 1,  4],
       [25, 36]])

Array Functions

In [86]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([  0,  45, 120, 231])

In [88]:
# mean/median/std/var
np.var(a1,axis=1)

array([1.25, 1.25, 1.25])

In [90]:
# trigonometric functions
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [92]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [94]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

Indexing and Slicing

In [97]:
a2[0:2,1:2]

array([[1],
       [5]])

In [99]:
a1[2:5:2]

array([[ 8,  9, 10, 11]])

In [101]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [103]:
a1[0:1,::]

array([[0, 1, 2, 3]])